### ISSUE TITLE
Need other dataset?

### ISSUE THREAD

**Issue by caoql98** [fanq15/FSOD-code#18]
Thanks for your code. I have fininshed the training phase, but when I run the test_net.py, I find a AssertionError: Image set path does not exist: data/VOC_tes/ImageSets/Main/new_val.txt. So I still need  to add other dataset into the file?

**Comment by fanq15** [comment]
Could you give me more information about your bug? It is better if you provide the bug picture.

**Comment by caoql98** [comment]
thanks for your reply, the bug shows as bellow:
INFO test_engine.py: 224: Wrote detections to: /home/caoqinglong/object_detection/FSOD-code-master/Outputs/fsod_save_dir/test/detections.pkl
INFO test_engine.py: 174: Total inference time: 8864.734s
INFO task_evaluation.py:  75: Evaluating detections
Traceback (most recent call last):
  File "tools/test_net.py", line 132, in <module>
    check_expected_results=True)
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/core/test_engine.py", line 132, in run_inference
    all_results = result_getter()
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/core/test_engine.py", line 111, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/core/test_engine.py", line 176, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, output_dir
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/task_evaluation.py", line 59, in evaluate_all
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/task_evaluation.py", line 80, in evaluate_boxes
    dataset, all_boxes, output_dir, use_matlab=use_matlab)
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/voc_dataset_evaluator.py", line 48, in evaluate_boxes
    filenames = _write_voc_results_files(json_dataset, all_boxes, salt)
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/voc_dataset_evaluator.py", line 64, in _write_voc_results_files
    'Image set path does not exist: {}'.format(image_set_path)
AssertionError: Image set path does not exist: data/VOC_tes/ImageSets/Main/new_val.txt

**Comment by fanq15** [comment]
What's the `VOC_tes`?

**Comment by caoql98** [comment]
This is exactly what I don not know

**Comment by fanq15** [comment]
Emmm, I have never met it. Let me check it.

**Comment by fanq15** [comment]
You can update the code and try the test procedure again. You can set a small number here for faster test: [episode_num in json_dataset.py](https://github.com/fanq15/FSOD-code/blob/3feabd78f4d70776deb67dc97c638bc9df2eaaf5/lib/datasets/json_dataset.py#L178) and [episode_num in test_engine.py](https://github.com/fanq15/FSOD-code/blob/3feabd78f4d70776deb67dc97c638bc9df2eaaf5/lib/core/test_engine.py#L593)

**Comment by caoql98** [comment]
Thanks for your answer,  but another bug shows as follow:
INFO test_engine.py: 174: Total inference time: 152.861s
INFO task_evaluation.py:  75: Evaluating detections
INFO voc_dataset_evaluator.py:  79: Writing VOC results for: drinking straw_0
Traceback (most recent call last):
  File "tools/test_net.py", line 132, in <module>
    check_expected_results=True)
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/core/test_engine.py", line 132, in run_inference
    all_results = result_getter()
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/core/test_engine.py", line 111, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/core/test_engine.py", line 176, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, output_dir
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/task_evaluation.py", line 59, in evaluate_all
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/task_evaluation.py", line 80, in evaluate_boxes
    dataset, all_boxes, output_dir, use_matlab=use_matlab)
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/voc_dataset_evaluator.py", line 48, in evaluate_boxes
    filenames = _write_voc_results_files(json_dataset, all_boxes, salt)
  File "/home/caoqinglong/object_detection/FSOD-code-master/lib/datasets/voc_dataset_evaluator.py", line 84, in _write_voc_results_files
    with open(filename, 'wt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOC_tes/Results/drinking straw_0.txt'

**Comment by caoql98** [comment]
Thanks for your help, I have solved the issue by  change 'return os.path.join('data/VOC' + year, 'Results', '{:s}.txt')' to  'return os.path.join('data/fsod', '{:s}.txt')', by the way another issure emgerd after the issue sloved, and I solved it by comment the line 124-127in voc_dataset_evaluator and set the use_07_metric = True.

**Comment by zhoushuang66** [comment]
> Thanks for your help, I have solved the issue by change 'return os.path.join('data/VOC' + year, 'Results', '{:s}.txt')' to 'return os.path.join('data/fsod', '{:s}.txt')', by the way another issure emgerd after the issue sloved, and I solved it by comment the line 124-127in voc_dataset_evaluator and set the use_07_metric = True.

I met the same problem,in this way, can we get the results of the paper experiment?
