### ISSUE TITLE
How to show result of testing?

### ISSUE THREAD

**Issue by wlh0517** [fanq15/FSOD-code#25]
When I run testing code in "all.sh", it shows the below picture.

INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29911/30000 0.613s + 0.001s (eta: 0:00:54)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29921/30000 0.613s + 0.001s (eta: 0:00:48)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29931/30000 0.613s + 0.001s (eta: 0:00:42)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29941/30000 0.613s + 0.001s (eta: 0:00:36)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29951/30000 0.613s + 0.001s (eta: 0:00:30)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29961/30000 0.613s + 0.001s (eta: 0:00:23)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29971/30000 0.613s + 0.001s (eta: 0:00:17)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29981/30000 0.613s + 0.001s (eta: 0:00:11)
INFO test_engine.py: 330: im_detect: range [15001, 30000] of 30000: 29991/30000 0.613s + 0.001s (eta: 0:00:05)
/home/dd/software/anaconda3/envs/fsod/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "/home/dd/wlh/FSOD-code/tools/test_net.py", line 131, in <module>
    check_expected_results=True)
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 130, in run_inference
    all_results = result_getter()
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 127, in result_getter
    gpu_id=gpu_id
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 361, in test_net
    ), det_file
  File "/home/dd/wlh/FSOD-code/lib/utils/io.py", line 43, in save_object
    pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)
MemoryError

Traceback (most recent call last):
  File "tools/test_net.py", line 131, in <module>
    check_expected_results=True)
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 130, in run_inference
    all_results = result_getter()
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 110, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 165, in test_net_on_dataset
    args, dataset_name, proposal_file, num_images, num_classes, output_dir
  File "/home/dd/wlh/FSOD-code/lib/core/test_engine.py", line 197, in multi_gpu_test_net_on_dataset
    args.load_ckpt, args.load_detectron, opts
  File "/home/dd/wlh/FSOD-code/lib/utils/subprocess.py", line 107, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/dd/wlh/FSOD-code/lib/utils/subprocess.py", line 145, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)
(fsod) dd@dd-desktop:~/wlh/FSOD-code$ python

![image](https://user-images.githubusercontent.com/31612032/85130881-52941200-b268-11ea-8815-40537225f584.png)

How to solve this problem?
And I want to know how to show the picture after detection. I want to get the picture as that in your paper.

**Comment by wlh0517** [comment]
'all.sh' is 'CUDA_VISIBLE_DEVICES=0,1 python3 tools/test_net.py --multi-gpu-testing --dataset fsod --cfg configs/fsod/voc_e2e_faster_rcnn_R-50-C4_1x_old_1.yaml --load_ckpt Outputs/fsod36000/ckpt/model_step71999.pth
'

**Comment by TMoonLi** [comment]
I encountered the same problem as you, did you solve it?

**Comment by AmingWu** [comment]
@wlh156423 , did you solve this problem? I also encountered the same problem.

**Comment by liuweijie19980216** [comment]
I also met this problem,maybe it's because the computer doesn't have enough memory.
Then I changed the compute that has memory of 32G and worked well.

**Comment by fhong-jpg** [comment]
@liuweijie19980216 Could you share me the trained model? Thanks.
