### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by yyyyojiro** [fanq15/FSOD-code#48]
when I run train_net_step.py, the following error occurred...

Traceback (most recent call last):
  File "tools/train_net_step.py", line 493, in <module>
    main()
  File "tools/train_net_step.py", line 372, in main
    load_detectron_weight(maskRCNN, args.load_detectron)
  File "/home/thinkstation-3/LIVA/LS/Data/FSOD/code_files/lib/utils/detectron_weight_helper.py", line 12, in load_detectron_weight
    with open(detectron_weight_file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'data/pretrained_model/model_final.pkl'
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1e4e0010b8>>
Traceback (most recent call last):
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/thinkstation-3/anaconda3/envs/fsod/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

I really put the model_final.plk in the data/pretrained_moedel directory, but the FileNotFoundError always occurred. Other errors are also posted here, could you give me any advice? Thanks a lot !

-

**Comment by yyyyojiro** [comment]
I download the model_final.pkl one more time, and I solved this problem..
