### ISSUE TITLE
when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137)

### ISSUE THREAD

**Issue by yyyyojiro** [fanq15/FSOD-code#50]
Traceback (most recent call last):
  File "tools/test_net.py", line 131, in <module>
    check_expected_results=True)
  File "/home/amax-6/LIVA/LI_S/fsod/code_files/lib/core/test_engine.py", line 134, in run_inference
    all_results = result_getter()
  File "/home/amax-6/LIVA/LI_S/fsod/code_files/lib/core/test_engine.py", line 112, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/amax-6/LIVA/LI_S/fsod/code_files/lib/core/test_engine.py", line 170, in test_net_on_dataset
    args, dataset_name, proposal_file, num_images, num_classes, output_dir, dataset
  File "/home/amax-6/LIVA/LI_S/fsod/code_files/lib/core/test_engine.py", line 202, in multi_gpu_test_net_on_dataset
    args.load_ckpt, args.load_detectron, opts
  File "/home/amax-6/LIVA/LI_S/fsod/code_files/lib/utils/subprocess.py", line 107, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/amax-6/LIVA/LI_S/fsod/code_files/lib/utils/subprocess.py", line 145, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 137)

bash:CUDA_VISIBLE_DEVICES=0,1,2,3 python3 tools/test_net.py --multi-gpu-testing --dataset fsod --cfg configs/fsod/voc_e2e_faster_rcnn_R-50-C4_1x_old_1.yaml --load_ckpt Outputs/fsod_save_dir/ckpt/model_step59999.pth

 It has confused me several days, thanks very much!

**Comment by fhong-jpg** [comment]
@yyyyojiro Could you share me the trained model? Thanks.

**Comment by yyyyojiro** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 上午9:29
收件人:&nbsp;"fanq15/FSOD-code"<FSOD-code@noreply.github.com&gt;;
抄送:&nbsp;"only_Yojiro"<2402068371@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50)





 
@yyyyojiro Could you share me the trained model? Thanks.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

model_step59999.pth (416.56M, 2020年11月19日 21:37 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7a38316368cbc084a19f1dec1231044e015a04020d0302521f0e06050d1c02530b011c5b5750504c560f545102090050530a50073422360c5d5c540f6b424204420d085a0d0818114650315e&code=281c416a

**Comment by fhong-jpg** [comment]
@yyyyojiro Thank you for the sharing!

**Comment by zhanggaojian** [comment]
@yyyyojiro @fhong-jpg Could you share me the trained model? Thanks. When I compile the code and run sh make.sh，the error occured，Have you ever encountered this situation?

**Comment by yyyyojiro** [comment]
its been a long time....so I am not sure that the model is the final trained model,&nbsp; hope this model can help you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50)





 
@yyyyojiro @fhong-jpg Could you share me the trained model? Thanks. When I compile the code and run sh make.sh，the error occured，Have you ever encountered this situation?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

fsod_model_step59999.pth (416.56M, 2021年05月14日 11:44 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e6239663fcbc6d0a0c515e94531021a50510155000552531e070f555a1c04070201145e5008541802010a0007045603555a5f5463293053400d5d390e5e54505f3d4a120641050c0a5b0048134558350e&code=3b9fc105

**Comment by zhanggaojian** [comment]
Thank you. By the way, Have you run the test using FSOD Dataset successfully?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50)





 its been a long time....so I am not sure that the model is the final trained model,&amp;nbsp; hope this model can help you. 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年4月14日(星期三) 中午11:30 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50) 
 
 
 
 
 
   
 @yyyyojiro @fhong-jpg Could you share me the trained model? Thanks. When I compile the code and run sh make.sh，the error occured，Have you ever encountered this situation? 
   
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 
 从QQ邮箱发来的超大附件 
 
 fsod_model_step59999.pth (416.56M, 2021年05月14日 11:44 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;k=7e6239663fcbc6d0a0c515e94531021a50510155000552531e070f555a1c04070201145e5008541802010a0007045603555a5f5463293053400d5d390e5e54505f3d4a120641050c0a5b0048134558350e&amp;code=3b9fc105

**Comment by yyyyojiro** [comment]
yes, but I havn't recorded the log&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50)





 Thank you. By the way, Have you run the test using FSOD Dataset successfully? 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年4月14日(星期三) 中午11:54 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50) 
 
 
 
 
 
  its been a long time....so I am not sure that the model is the final trained model,&amp;amp;nbsp; hope this model can help you.  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "fanq15/FSOD-code"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年4月14日(星期三) 中午11:30  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [fanq15/FSOD-code] when I run test_net.py, occured AssertionError: Range subprocess failed (exit code: 137) (#50)  
   
   
   
   
   
     
  @yyyyojiro @fhong-jpg Could you share me the trained model? Thanks. When I compile the code and run sh make.sh，the error occured，Have you ever encountered this situation?  
     
  —  
  You are receiving this because you were mentioned.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
   
   
  从QQ邮箱发来的超大附件  
   
  fsod_model_step59999.pth (416.56M, 2021年05月14日 11:44 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;amp;k=7e6239663fcbc6d0a0c515e94531021a50510155000552531e070f555a1c04070201145e5008541802010a0007045603555a5f5463293053400d5d390e5e54505f3d4a120641050c0a5b0048134558350e&amp;amp;code=3b9fc105

**Comment by xiaofeng-c** [comment]
i meet the same problem as you,have you solved it?@yyyyojiro

**Comment by yyyyojiro** [comment]
> i meet the same problem as you,have you solved it?@yyyyojiro

sorry, I forgot it, Maybe it can be solved without using multi-gpu?

**Comment by gmkproofing** [comment]
> > i meet the same problem as you,have you solved it?@yyyyojiro
> 
> sorry, I forgot it, Maybe it can be solved without using multi-gpu?

Hi, when I use only one gpu, another problem occuered :
"INFO test_engine.py: 541: loading checkpoint Outputs/fsod_save_dir/ckpt/model_step59999.pth
Killed
"
Did you met this problem?
Looking forward to your help, thank you !!!

**Comment by yyyyojiro** [comment]
> > > i meet the same problem as you,have you solved it?@yyyyojiro
> > 
> > 
> > sorry, I forgot it, Maybe it can be solved without using multi-gpu?
> 
> Hi, when I use only one gpu, another problem occuered : "INFO test_engine.py: 541: loading checkpoint Outputs/fsod_save_dir/ckpt/model_step59999.pth Killed " Did you met this problem? Looking forward to your help, thank you !!!

I am so sorry that I forgot it....
