### ISSUE TITLE
a  question for running

### ISSUE THREAD

**Issue by Zyt-wenwne** [fanq15/FSOD-code#61]
there are some questions when run the all.sh,how can l run the code withou error

Traceback (most recent call last):
  File "tools/train_net_step.py", line 30, in <module>
    from modeling.model_builder import Generalized_RCNN
  File "/home/zytr/桌面/FSOD-code-master/lib/modeling/model_builder.py", line 11, in <module>
    from model.roi_pooling.functions.roi_pool import RoIPoolFunction
  File "/home/zytr/桌面/FSOD-code-master/lib/model/roi_pooling/functions/roi_pool.py", line 3, in <module>
    from .._ext import roi_pooling
  File "/home/zytr/桌面/FSOD-code-master/lib/model/roi_pooling/_ext/roi_pooling/__init__.py", line 2, in <module>
    from ._roi_pooling import lib as _lib, ffi as _ffi
ImportError: /home/zytr/桌面/FSOD-code-master/lib/model/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: __cudaPopCallConfiguration
Traceback (most recent call last):
  File "tools/test_net.py", line 14, in <module>
    from core.test_engine import run_inference
  File "/home/zytr/桌面/FSOD-code-master/lib/core/test_engine.py", line 37, in <module>
    from datasets import task_evaluation
  File "/home/zytr/桌面/FSOD-code-master/lib/datasets/task_evaluation.py", line 47, in <module>
    import datasets.voc_dataset_evaluator as voc_dataset_evaluator
  File "/home/zytr/桌面/FSOD-code-master/lib/datasets/voc_dataset_evaluator.py", line 167
    assert os.path.exists(filedir):
                                  ^

**Comment by Vidar-Sirius** [comment]
去这个文件里voc_dataset_evaluator.py 把冒号删了就行
